### ISSUE TITLE
Partition keys without version causes the containers.openOrCreate to throw exception

### ISSUE THREAD

**Issue by carlkenne** [d-markey/azure_cosmosdb#12]
BadResponseException: Expected a value of type 'int', but got one of type 'Null'

Apparently the older Partition Keys doesn't contain "version". But version is non-null in the PartitionKeySpec (when calling fromJson in the partition_key_spec.dart). My container was created in 2022. If I create a new container then it works fine. From what I read, the only way to fix this is to create a new container and migrate all data.

**Comment by d-markey** [comment]
Hello,

I've pushed an update to github so that version-less `PartitionKeySpecs` can be deserialized from JSON.

Can you try with this version? To do so you can add a `dependency_overrides` entry to your pubspec:

```yaml
dependency_overrides:
  azure_cosmosdb:
    git: https://github.com/d-markey/azure_cosmosdb.git
```

If it works, I will publish a new version to [pub.dev](https://pub.dev/packages/azure_cosmosdb). Otherwise please provide the exception message including the stack trace.

**Comment by carlkenne** [comment]
Thanks, works perfectly now! @d-markey

**Comment by d-markey** [comment]
New version published!
